"""
Prompt templates for meeting insight extraction.

Extraction uses Claude's tool-use feature: the MeetingInsights JSON schema is
passed as a tool definition and tool_choice is forced, so the model must
respond with schema-conformant structured output rather than free text that
would need brittle parsing.
"""

EXTRACTION_SYSTEM_PROMPT = """\
You are a precise meeting analyst. You read raw meeting transcripts (often \
auto-generated by ASR and containing minor transcription errors, filler \
words, or unclear speaker attribution) and extract exactly what was decided \
and what needs to happen next.

Rules:
- Only report information that is actually present or clearly implied in the transcript. Never invent names, deadlines, or decisions.
- If an assignee or deadline is not stated, leave it null — do not guess.
- Each action item must be a single, concrete, actionable task, not a vague theme.
- Priority reflects urgency as expressed in the meeting (explicit deadlines, escalation language, blocking dependencies = high; routine follow-ups = medium; nice-to-haves or loosely-timed items = low).
- The executive summary should be usable by someone who did not attend the meeting: what was the meeting about, what mattered, what changed.
- Correct obvious ASR transcription artifacts (e.g. garbled words) only when the correction is unambiguous from context; otherwise leave as-is.
- Respond only by calling the extract_meeting_insights tool. Do not produce any other text.
"""

EXTRACTION_USER_TEMPLATE = """\
Extract structured insights from the following meeting transcript.

<transcript>
{transcript}
</transcript>

Call the extract_meeting_insights tool with your findings."""


# --- Used only for the map-reduce path on very long transcripts ---
CHUNK_SUMMARY_SYSTEM_PROMPT = """\
You are summarizing one segment of a longer meeting transcript. Produce a \
dense, factual bullet-point summary covering: topics discussed, any \
decisions made, and any tasks/commitments mentioned (with assignee and \
deadline if stated). This summary will later be merged with summaries of \
other segments from the same meeting, so preserve concrete details — do not \
generalize them away. Do not add commentary or headers, just the bullets."""

CHUNK_SUMMARY_USER_TEMPLATE = """\
<transcript_segment index="{index}" of="{total}">
{segment}
</transcript_segment>

Summarize this segment as dense bullet points."""

REDUCE_USER_TEMPLATE = """\
The following are dense bullet-point summaries of consecutive segments of \
one meeting, in order. Synthesize them into a single coherent set of \
insights for the meeting as a whole, then call the extract_meeting_insights \
tool with your findings. Merge duplicate or related items across segments \
rather than listing them separately.

<segment_summaries>
{combined_summaries}
</segment_summaries>

Call the extract_meeting_insights tool with your findings."""
